version: "3"

services:
  bootstrap:
    image: consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command:
      - agent
      - -server
      - -bootstrap-expect=1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
  server:
    image: consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command:
      - agent
      - -server
      - -retry-join=bootstrap
      - -retry-join=server
      - -ui
      - -client=0.0.0.0
    ports:
      - "8500:8500"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
  client:
    image: consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command:
      - agent
      - -retry-join=server
      - -ui
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

# order: start-first

# check vagrant sample for more options
#   datacenter:
#   "acl_agent_token": "",
#   "acl_datacenter": "dc1",
#   "acl_default_policy": "deny",
#   "acl_master_token": "",
#   "encrypt": "",
