version: '3'

services:
  server:
    image: library/vault:0.11.5
    volumes:
      - server_config:/vault/config
    networks:
      - default
      - consul
    ports:
      - 8200:8200
    command:
      - server
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux

volumes:
  server_config:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/.docker/volumes/vault/server/config
      o: bind

networks:
  default:
  consul:
    external:
      name: consul_default
