version: '3'

services:
  server:
    image: library/registry:2.6.2
    volumes:
      - server_data:/var/lib/registry
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux

volumes:
  server_data:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/.docker/volumes/registry/server/data
      o: bind
