version: '3'

services:
  default:
    image: library/registry:2.6.2
    volumes:
      - /data/docker/swarm/registry/default/data:/var/lib/registry
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
