version: "3"

services:
  linux:
    image: alpine:latest
    command: ping docker.com
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
  windows:
    image: microsoft/nanoserver:latest
    command: ping -t docker.com
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == windows
