require "#{File.dirname(__FILE__)}/../../../src/core/vagrant"

VagrantProvider.defaults('memory' => 2048, 'cpus' => 2)

deployment = VagrantDeployment.new(File.dirname(__FILE__))
deployment.configure
