version: '3.2'

services:
  bootstrap:
    image: library/consul:1.4.0
    volumes:
      - bootstrap_config:/consul/config
    networks:
      default:
        aliases:
          - join
    command:
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
  server:
    image: library/consul:1.4.0
    volumes:
      - server_config:/consul/config
      - server_data:/consul/data
    command:
      - agent
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
  client:
    image: library/consul:1.4.0
    volumes:
      - client_config:/consul/config
    ports:
      - 8500:8500
    command:
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux

volumes:
  bootstrap_config:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/.docker/volumes/consul/bootstrap/config
      o: bind
  server_config:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/.docker/volumes/consul/server/config
      o: bind
  server_data:
  client_config:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/.docker/volumes/consul/client/config
      o: bind

networks:
  default:
