version: "3.2"

services:
  bootstrap:
    image: consul:1.2.2
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command:
      - agent
      - -server
      - -bootstrap-expect=1
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
  server:
    image: consul:1.2.2
    volumes:
      - data:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command:
      - agent
      - -server
      - -retry-join=bootstrap
      - -ui
      - -client=0.0.0.0
    ports:
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
  client:
    image: consul:1.2.2
    volumes:
      - data:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command:
      - agent
      - -retry-join=server
      - -ui
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

volumes:
  data:

# order: start-first

# check vagrant sample for more options
#   datacenter:
#   "acl_agent_token": "",
#   "acl_datacenter": "dc1",
#   "acl_default_policy": "deny",
#   "acl_master_token": "",
#   "encrypt": "",
