version: '3.2'

services:
  bootstrap:
    image: library/consul:1.2.2
    volumes:
      - /data/docker/volumes/consul/bootstrap/config:/consul/config
    networks:
      default:
        aliases:
          - server_join
    command:
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
  server:
    image: library/consul:1.2.2
    volumes:
      - /data/docker/volumes/consul/server/config:/consul/config
      - server_data:/consul/data
    command:
      - agent
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
  client:
    image: library/consul:1.2.2
    volumes:
      - /data/docker/volumes/consul/client/config:/consul/config
    ports:
      - 8500:8500
    command:
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux

volumes:
  server_data:

networks:
  default:

# order: start-first

# check vagrant sample for more options
#   datacenter:
#   "acl_agent_token": "",
#   "acl_datacenter": "dc1",
#   "acl_default_policy": "deny",
#   "acl_master_token": "",
#   "encrypt": "",
