version: "3"

services:
  linux:
    image: alpine:3.8
    command: ping docker.com
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
  windows:
    image: microsoft/nanoserver:10.0.14393.2430
    command: ping -t docker.com
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == windows
