version: '3'

services:
  master:
    image: jenkinsci/blueocean:1.9.0
    volumes:
      - master_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux

volumes:
  master_data:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/.docker/volumes/jenkins/master/data
      o: bind
