version: '3'

services:
  master:
    image: jenkinsci/blueocean:1.8.2
    volumes:
      - /data/docker/swarm/jenkins/master/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
